### ISSUE TITLE
choose one canonical repository

### ISSUE THREAD

**Issue by thkoch2001** [jens-maus/carddav2fb#7]
There are several forks of carddav2fb and it's hard to choose the best one. And it's not clear where's the best place to fill issues.

**Comment by jens-maus** [comment]
Well, I am all for unifying the repositories again. However, carlos22 seems not to be active anymore thus I initially decided to continue development in this repository instead. And then I also merged all different changes from different carddav2fb forks. Thus, I feel that my repository currently represents the latest state of the art. But if you feel we should still unify the repositories again feel free to contact carlos22 and the others so that we can work on that.

**Comment by thkoch2001** [comment]
The best would be if carlos22 would transfer his repository to you. For this you need to delete your fork and than he can transfer his repository to your account. Therefor it would be best if you could try to contact @carlos22.

**Comment by jens-maus** [comment]
I think it would be best to first try to merge in all the changes of this repository to the original carlos22/carddav2fb repository and then transfer the ownership because this should keep the history in proper order.

I have therefore created a unification pull request (https://github.com/carlos22/carddav2fb/pull/6) for carlos22 and hope he will accept my proposal.
